### PR TITLE
Make the code samples runnable

### PR DESCRIPTION
**Pull request by codypiersall**
Make the code samples from the original README runnable with this project.
Note:  I couldn't run the examples that used `mlp`; maybe they should be updated to use something else?

### CODE REVIEW

**Comment by ewiger** [comment]
mlab and matlab are two diff things. the injection of matlab into the scope of importing model is implicit. "as matlab" is not required (I know it is ugly).

**Comment by codypiersall** [comment]
If the name "matlab" were injected into the importer's namespace, you should be able to do

    >>> from mlab.releases import latest_release
    >>> matlab
    <mlab.mlabwrap.MlabWrap object at 0x00000000034E3EB8>

But as it is, this code results in

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    NameError: name 'matlab' is not defined

Or am I misunderstanding what you meant?  I'm testing on Python 2.7.9, 64-bit for Windows.

**Comment by ewiger** [comment]
windows is not supported :(

**Comment by codypiersall** [comment]
Ah!  If I can find some time at work tomorrow I'll see if I can install Matlab on a Linux VM.  I'm not sure how our licensing works, but if I can test the differences I'll give it a shot.

Everything I've tried so far does _work_ on Windows, but maybe it's just a happy coincidence?

**Comment by lrq3000** [comment]
It works for me on Windows 7 x64!

**Pull request merged**
